/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.UserOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kiran
 */
public class DoctorRatingsPanel extends javax.swing.JPanel {

        private Enterprise enterprise;
        private JPanel userProcessContainer;
        private UserAccount userAccount;
        private EcoSystem business;
        private  UserOrganization userOrganization;
   

   public DoctorRatingsPanel(Enterprise enterprise, JPanel userProcessContainer, UserAccount userAccount, UserOrganization userOrganization, EcoSystem business) {
        initComponents();
         this.enterprise= enterprise;
                   this.userProcessContainer = userProcessContainer;
                   this.enterprise = enterprise;
                   this.userAccount = userAccount;
                   this.business = business;
                   this.userOrganization = userOrganization;
                  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        maleJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        femaleJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/doc2.jpg"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/doc3.jpg"))); // NOI18N

        maleJButton.setBackground(new java.awt.Color(0, 0, 51));
        maleJButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        maleJButton.setForeground(new java.awt.Color(255, 255, 255));
        maleJButton.setText("\n\nBook An Appointment\n\n\n");
        maleJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleJButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Name :  John Gowda\nAge  :  55\nSpec :  Physician\nAddress : 614A Shawmut Avenue \nRatings : 4.1/5\n\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Name :  Mary \nAge  :  45\nSpec :  Physician\nAddress : 314A Huntington Avenue \nRatings : 4.5/5\n\n\n");
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea2.setDragEnabled(true);
        jScrollPane2.setViewportView(jTextArea2);

        femaleJButton.setBackground(new java.awt.Color(0, 0, 51));
        femaleJButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        femaleJButton.setForeground(new java.awt.Color(255, 255, 255));
        femaleJButton.setText("\n\nBook An Appointment\n\n\n");
        femaleJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(maleJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2)
                    .addComponent(femaleJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleJButton)
                    .addComponent(femaleJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void maleJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleJButtonActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("userToDoctorPanel", new userToDoctorPanel(enterprise,userProcessContainer, userAccount,userOrganization, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_maleJButtonActionPerformed

    private void femaleJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleJButtonActionPerformed
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("userToDoctorPanel", new userToDoctorPanel(enterprise,userProcessContainer, userAccount,userOrganization, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_femaleJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton femaleJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton maleJButton;
    // End of variables declaration//GEN-END:variables
}
