/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.UserOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.UserRole.userToOrganBankJPanel;

/**
 *
 * @author kiran
 */
public class UserWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserWorkAreaJPanel
     */
    
private JPanel userProcessContainer;
private UserAccount userAccount;
private UserOrganization userOrganization;
private Enterprise enterprise;
private EcoSystem business;
//private DoctorOrganization doctorOrganization;
    public UserWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, UserOrganization userOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.userOrganization = userOrganization;
        this.enterprise = enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestDoctorTreatmentbtn = new javax.swing.JButton();
        donateOrganbtn = new javax.swing.JButton();
        donateBloodButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rewardsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        requestDoctorTreatmentbtn.setBackground(new java.awt.Color(153, 0, 0));
        requestDoctorTreatmentbtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        requestDoctorTreatmentbtn.setForeground(new java.awt.Color(255, 255, 255));
        requestDoctorTreatmentbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/teatment_icon.jpg"))); // NOI18N
        requestDoctorTreatmentbtn.setText("Request Treatment");
        requestDoctorTreatmentbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        requestDoctorTreatmentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestDoctorTreatmentbtnActionPerformed(evt);
            }
        });

        donateOrganbtn.setBackground(new java.awt.Color(153, 0, 0));
        donateOrganbtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        donateOrganbtn.setForeground(new java.awt.Color(255, 255, 255));
        donateOrganbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/heart_icon.jpg"))); // NOI18N
        donateOrganbtn.setText("Donate Organ");
        donateOrganbtn.setMargin(new java.awt.Insets(2, 5, 2, 5));
        donateOrganbtn.setMaximumSize(new java.awt.Dimension(95, 37));
        donateOrganbtn.setMinimumSize(new java.awt.Dimension(95, 37));
        donateOrganbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateOrganbtnActionPerformed(evt);
            }
        });

        donateBloodButton.setBackground(new java.awt.Color(153, 0, 0));
        donateBloodButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        donateBloodButton.setForeground(new java.awt.Color(255, 255, 255));
        donateBloodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/drop.jpg"))); // NOI18N
        donateBloodButton.setText("Donate Blood ");
        donateBloodButton.setMargin(new java.awt.Insets(2, 5, 2, 5));
        donateBloodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateBloodButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/main_page.png"))); // NOI18N

        rewardsBtn.setBackground(new java.awt.Color(0, 0, 153));
        rewardsBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        rewardsBtn.setForeground(new java.awt.Color(255, 255, 255));
        rewardsBtn.setText("Register for Rewards");
        rewardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rewardsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(requestDoctorTreatmentbtn)
                .addGap(36, 36, 36)
                .addComponent(donateOrganbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(donateBloodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rewardsBtn)
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestDoctorTreatmentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donateOrganbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donateBloodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(rewardsBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestDoctorTreatmentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestDoctorTreatmentbtnActionPerformed
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("userToDoctorPanel", new DoctorRatingsPanel(enterprise,userProcessContainer, userAccount,userOrganization, business));
        layout.next(userProcessContainer);
       
       
       

    }//GEN-LAST:event_requestDoctorTreatmentbtnActionPerformed

    private void donateOrganbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateOrganbtnActionPerformed
         CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("userToOrganBankJPanel", new userToOrganBankJPanel(enterprise,userProcessContainer, userAccount,userOrganization, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_donateOrganbtnActionPerformed

    private void donateBloodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateBloodButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("UserToBloodBankJPanel", new UserToBloodBankJPanel(enterprise,userProcessContainer, userAccount,userOrganization, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_donateBloodButtonActionPerformed

    private void rewardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rewardsBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("UserToRewardsJPanel", new UserToRewardsJPanel(enterprise,userProcessContainer, userAccount,userOrganization, business));
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_rewardsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donateBloodButton;
    private javax.swing.JButton donateOrganbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton requestDoctorTreatmentbtn;
    private javax.swing.JButton rewardsBtn;
    // End of variables declaration//GEN-END:variables
}
