/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Pharma;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PharmaOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BloodBankWorkRequest;
import Business.WorkQueue.PharmacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kiran
 */
public class PharmaWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmaWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private PharmaOrganization pharmaOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
   
    public PharmaWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, PharmaOrganization pharmaOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.pharmaOrganization = pharmaOrganization;
        this.enterprise = enterprise;
        this.business = business;
        populatePharmaTable();
    }
    
    public void populatePharmaTable(){
        DefaultTableModel model = (DefaultTableModel) pharm_Jtable.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request : pharmaOrganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            PharmacyWorkRequest pharmaRequest = (PharmacyWorkRequest) request;
        row[0] = pharmaRequest.getDoctortoPharmaDoctorName();
        row[1] = pharmaRequest.getDoctortoPharmaMedicineName();
        row[2] = pharmaRequest.getDoctortoPharmaQuantity();
        row[3] = pharmaRequest.getStatus();
        row[4] = pharmaRequest;
        model.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pharm_Jtable = new javax.swing.JTable();
        processBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pharm_Jtable.setBackground(new java.awt.Color(162, 220, 249));
        pharm_Jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Doctor Name", "Medicine", "Quantity", "Status", "AllDetails"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pharm_Jtable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(pharm_Jtable);

        processBtn.setBackground(new java.awt.Color(0, 0, 102));
        processBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        processBtn.setForeground(new java.awt.Color(255, 255, 255));
        processBtn.setText("Click to Send Medicines");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Pharmacy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(processBtn)
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = pharm_Jtable.getSelectedRow();
       
        if (selectedRow < 0){
            return;
        }
       
        WorkRequest request = (WorkRequest)pharm_Jtable.getValueAt(selectedRow, 4);
       
        request.setStatus("Medicine supplied");
        populatePharmaTable();
    }//GEN-LAST:event_processBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pharm_Jtable;
    private javax.swing.JButton processBtn;
    // End of variables declaration//GEN-END:variables
}
